### ISSUE TITLE
目標 (v2)

### ISSUE THREAD

**Issue by vain0x** [vain0x/knowbug#66]
v2 は knowbug の新しいバージョンです。

## 目標

- [x] 自動テストの仕組みの作成 (refs #12)
- [x] メンテナンス性を阻害する機能の削除 (refs #38)
- [x] ソースコードの改善 (HspObjectPath の導入ほか refs #31 refs #68)
- [x] UTF-8 版対応 (refs #26)
- [x] ~~オブジェクトツリーの動的ノード~~
    - 配列の要素などもツリービューのノードとして実行時に増減させる機能。実装の複雑さが予想以上に高く、そのわりに使いにくさがあったので、中断しました。
- [x] サーバー(DLL)・クライアント(HSP)構成への移行 (refs #70)
- [x] リストボックスUIへの転換
- [x] クライアントの未実装機能の再実装
- [x] クライアントの不具合の修正
- [x] 通信の非同期化
- [x] ~~オブジェクトキーへの転換 (refs #31)~~ 先送り
- [x] 不要コードの削除

## クライアントの未実装機能

まだリリースされていない機能にもチェックがついていることもあるのでご了承ください。

- [x] クライアントの表示位置・サイズを設定ファイルからロードする
- [x] 右クリックメニューで「ウィンドウを最前面に表示する」を追加する
    - [x] 最前面かどうかは設定ファイルからロードする
- [x] クライアントの各種フォントを設定ファイルからロードする
- [x] ~~リストビューのノードの「開閉」を可能ならクライアント側で実装する~~ 開閉は本質なので不可能 (オブジェクトを手動で開かせることで無限のグラフを有限のデータに落とせている。DAPも同様)
- [x] リストビューのカラムの幅をウィンドウのサイズに合わせて自動調整する
- [x] スクリプトエディットの上に ~~行番号~~ と絶対パスを表示する欄を追加する
- [x] スクリプトエディットの上に「ソースファイルを開く」ボタンを追加する
- [x] ログエディットの更新を 60回/秒 に制限する
- [x] ログの自動保存をクライアント側で実装する
- [x] 右クリックメニューで「ログの全消去」を追加する
- [x] 右クリックメニューで「ログの保存」を追加する
- [x] ステップ実行で次飛(ステップオーバー)・脱出(ステップアウト)機能を追加する
- [x] 詳細ウィンドウを適度に更新する
- [x] 設定ファイルを開くメニュー

## クライアントの既知の不具合

v2.0.0-beta3 の不具合:

- [x] カンマ (`,`) を含む文字列や、多次元配列の要素がうまく表示されない
